# Generated by Django 4.2.1 on 2026-03-05 16:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student')], db_index=True, default='student', help_text='Primary role that governs default permissions.', max_length=20)),
                ('bio', models.TextField(blank=True, default='', help_text="Short biography displayed on the user's profile page.")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Instructions shown to students. Supports Markdown.')),
                ('assignment_type', models.CharField(choices=[('essay', 'Essay'), ('code', 'Code'), ('quiz', 'Quiz'), ('file_upload', 'File Upload')], default='essay', max_length=20)),
                ('due_date', models.DateTimeField(help_text='Deadline for on-time submission.')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum achievable score for this assignment.', max_digits=7)),
                ('late_policy', models.CharField(choices=[('none', 'None'), ('penalize', 'Penalize'), ('reject', 'Reject')], default='none', help_text='How late submissions are handled.', max_length=20)),
                ('rubric', models.JSONField(blank=True, help_text="Structured rubric for grading. Format: [{'criterion': str, 'max_points': int, 'description': str}, ...]", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Unpublished assignments are invisible to students.')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['course', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier for the course.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown-formatted course description shown on the catalogue page.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('max_enrollment', models.PositiveIntegerField(default=50, help_text='Maximum number of active enrollments allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text="Course-level configuration. Keys may include: 'allow_late_submissions', 'grading_scheme', 'discussion_enabled'.")),
                ('instructor', models.ForeignKey(help_text='Primary instructor responsible for this course.', on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Must be globally unique.', max_length=255, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Org-level configuration (branding, feature flags, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive orgs are hidden from listings.')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Opening post content. Supports Markdown.')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Pinned threads appear at the top of the thread list.')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked threads reject new posts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.course')),
            ],
            options={
                'verbose_name': 'thread',
                'verbose_name_plural': 'threads',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Submission version; incremented on each resubmission.')),
                ('content', models.TextField(blank=True, default='', help_text='Inline submission content (text, code, etc.).')),
                ('file_path', models.CharField(blank=True, help_text='Path to uploaded file in object storage, if applicable.', max_length=512, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('grading', 'Grading'), ('graded', 'Graded'), ('returned', 'Returned')], db_index=True, default='draft', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['-version'],
                'unique_together': {('assignment', 'student', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Post body. Supports Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent post for nested replies. Null for top-level posts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.thread')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('grade', 'Grade'), ('discussion', 'Discussion'), ('assignment', 'Assignment'), ('system', 'System')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Full notification body.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='PK of the related object (assignment, thread, etc.).', null=True)),
                ('related_content_type', models.CharField(blank=True, help_text='App-label.model string identifying the related object type.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(help_text='Display position within the course. Lower = earlier.')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Unpublished modules are invisible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('document', 'Document'), ('interactive', 'Interactive')], default='text', help_text='Determines the rendering strategy for the content field.', max_length=20)),
                ('content', models.TextField(blank=True, default='', help_text='Lesson body. Interpretation depends on content_type.')),
                ('order', models.PositiveIntegerField(help_text='Display position within the module.')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete, in minutes.', null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, default='', help_text='Academic department or team within the organization.', max_length=255)),
                ('office_hours', models.TextField(blank=True, default='', help_text='Free-text description of availability for students.')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Cached aggregate rating (1.00–5.00). Recomputed by analytics job.', max_digits=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'instructor profile',
                'verbose_name_plural': 'instructor profiles',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Points awarded for this submission.', max_digits=7)),
                ('feedback', models.TextField(blank=True, default='', help_text='Written feedback to the student.')),
                ('rubric_scores', models.JSONField(blank=True, help_text="Per-criterion scores matching the assignment rubric. Format: [{'criterion': str, 'score': int, 'comment': str}, ...]", null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(db_index=True, default=False, help_text='If True, this grade is used for official records and cache refresh.')),
                ('grader', models.ForeignKey(help_text='The user (instructor or peer) who assigned this grade.', on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.submission')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Mean final grade percentage across all completed enrollments.', max_digits=5, null=True)),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Percentage of enrollments that reached 'completed' status.", max_digits=5, null=True)),
                ('active_students', models.PositiveIntegerField(default=0, help_text='Count of currently active enrollments.')),
                ('total_submissions', models.PositiveIntegerField(default=0, help_text='Lifetime count of submissions across all assignments.')),
                ('last_calculated', models.DateTimeField(blank=True, help_text='When the analytics were last refreshed.', null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.course')),
            ],
            options={
                'verbose_name': 'course analytics',
                'verbose_name_plural': 'course analytics',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this course.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Optional: restrict this assignment to a specific module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.module'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('helpful', 'Helpful'), ('insightful', 'Insightful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reaction',
                'verbose_name_plural': 'reactions',
                'unique_together': {('post', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('grade', 'Grade'), ('discussion', 'Discussion'), ('assignment', 'Assignment'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='in_app', help_text='Delivery channel for this notification type.', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch. When False, this type is fully suppressed.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the student completed or was marked complete.', null=True)),
                ('final_grade_cache', models.DecimalField(blank=True, decimal_places=2, help_text='Cached final grade percentage. NOT the source of truth — recomputed from Grade records by the grade-cache refresh job.', max_digits=5, null=True)),
                ('course', models.ForeignKey(help_text='The course the student is enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('student', models.ForeignKey(help_text='The enrolled student.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
